name: Archibus-Automated-Scheduler-Albe

on:
  workflow_dispatch:
  schedule:
    - cron: "59 15 * * 1,4"  # 11:59 AM Eastern (EDT)



jobs:
  archibus-automated-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./ # use ./ for local dev.
        with:
          scheduling_args: ${{ secrets.Albert }} 
